CREATE OR REPLACE PROCEDURE LS_PROF
IS
CURSOR C IS
SELECT *
FROM PROFESOR;
fila PROFESOR%ROWTYPE;
BEGIN
OPEN C;
LOOP
FETCH C INTO fila;
EXIT WHEN C%NOTFOUND;
DBMS_OUTPUT.PUT_LINE(fila.DNI, fila.P, fila.CAR, fila.CAT);
END LOOP;
EXIT;
/
